config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root 'pages#index', as: :home_index
  delete '/pages/:id', to: 'pages#destroy', as: :destroy_empresa
  patch '/pages/:id', to: 'pages#update', as: :update_empresa
  get '/pages/:id/edit', to: 'pages#edit', as: :edit_empresa
  resources :user_sessions, only: [:new, :create, :destroy]
  get 'user_sessions/new', to: 'user_sessions#new', as: :login
  resources :users, only: [:index, :new, :create]
  get 'home/index', to: 'home#index', as: :home
  get 'users/new', to: 'users#create', as: :user_register
  get 'pages/export_csv/:id', to: 'pages#export_csv', as: 'export_csv'
  get 'pages/export_pdf/:id', to: 'pages#export_pdf', as: 'export_pdf'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  validates :nombre, :apellido, :departamento, :responsable_area, :extension, presence: true

  belongs_to :empresa
  has_many :equipos
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  validates :nombre, presence: true

  has_many :empleados, dependent: :destroy

  accepts_nested_attributes_for :empleados
end

app/models/equipo.rb
class Equipo < ApplicationRecord
  validates :serie, :modelo, :service_tag, :ip, :garantia, presence: true
  has_many :tipo_equipo
  belongs_to :marca
  belongs_to :estado
  belongs_to :empleado
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :equipos
end

app/models/marca.rb
class Marca < ApplicationRecord
  has_many :equipos
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/tipo_equipo.rb
class TipoEquipo < ApplicationRecord
  has_many :equipos
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password :password, validations: true
    validates :name, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
require 'csv'
require 'prawn/table'

class PagesController < ApplicationController
    # index is a public page
    def index
        @empresa = Empresa.includes(:empleados)
    end

    def new
        @empresa = Empresa.new
        @empresa.empleados.build
    end

    def create
        @empresa = Empresa.new(empresa_params)

        if @empresa.save
            redirect_to pages_path, notice: "Registro creado exitosamente"
        else
            render :new
        end
    end

    def destroy
        @empresa = Empresa.find(params[:id])
        @empresa.destroy
        redirect_to pages_path, notice: "Empresa ha sido eliminada"
    end

    def show
        @empresa = Empresa.includes(:empleados)
    end

    def edit
        @empresa = Empresa.find(params[:id])
    end

    def update
        @empresa = Empresa.find(params[:id])
        if @empresa.update(empresa_params)
            @empresa.save
            redirect_to pages_path, notice: 'Datos han sido actualizados'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def export_csv
        @empresa= Empresa.find(params[:id])
        csv_data = CSV.generate do |csv|
            csv << ["Bussiness Name", "Name", "Last Name", "Department", "Manager", "Phone line"]
            @empresa.empleados.each do |empleado|
                csv << [@empresa.nombre, empleado.nombre, empleado.apellido, empleado.departamento, empleado.responsable_area, empleado.extension]
            end    
        end
        send_data csv_data, filename: "Reporte.csv"    
    end
    
    def export_pdf
      @empresa= Empresa.find(params[:id])
      respond_to do |format|
        format.pdf do
          pdf = Prawn::Document.new

          logo_path = Rails.root.join('app', 'assets', 'images', 'logo.jpeg')

          if File.exist?(logo_path)
            pdf.image logo_path, width: 50, height: 50, position: :right
          else
            pdf.text "Logo no encontrado", color: "FF0000"  
          end

          pdf.text "Reporte de empleados para empresa #{@empresa.nombre}", size: 20, style: :bold
          pdf.move_down 10
          pdf.text "Fecha del Reporte: #{Time.zone.now.strftime('%d/%m/%Y %H:%M')}", align: :right

          data = [['Name', 'Last name', 'Department', 'Manager', 'Phone line']]
            
          @empresa.empleados.each do |empleado|
            data << [empleado.nombre, empleado.apellido, empleado.departamento, empleado.responsable_area, empleado.extension]
          end

          pdf.table(data, header: true, row_colors: ['dddddd', 'ffffff'], position: :center, width: pdf.bounds.width) do
            cells.border_width = 1
            cells.border_color = '000000'
            row(0).font_style = :bold
            self.header = true
          end

          send_data pdf.render, filename: 'reporte.pdf', type: 'application/pdf', disposition: 'inline'  
        end 
      end      
    end    

    private
    def empresa_params
        params.require(:empresa).permit(:nombre, empleados_attributes: [:id, :nombre, :apellido, :departamento, :responsable_area, :extension])
    end   
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
    @current_time = Time.now.strftime("%d-%m-%Y %R")
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to :controller => 'pages', :action => 'index'
    else
      flash[:alert] = "User or password incorrect."
      redirect_to new_user_session_path
    end    
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_index_path
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created succesfully"
      redirect_to home_index_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end    
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Your Logo</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Courses</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>

        </ul>
        <form class="">
          <%= link_to 'Login', login_path, class: 'btn btn-outline-success' %>
          <a class="btn btn-outline-success" href="#">Become member</a>
        </form>

      </div>
    </div>
  </nav>
</div>     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myinvtech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Holy, please check the info.</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<div class="d-flex flex-column min-vh-100">
    <%= render 'partials/header' %>
      <h1> Edit Info</h1>
    <div class="container border rounded my-3">
      <%= bootstrap_form_for @empresa, url: update_empresa_path do |f| %>
        <h2>Empresa</h2>
        <%= f.text_field :nombre, class: 'form-control' %>
        <h2>Empleado</h2>
        <%= f.fields_for(:empleados) do |empleado_form| %>
          <%= empleado_form.hidden_field :id %>
          <%= empleado_form.text_field :nombre, class: 'form-control' %>
          <%= empleado_form.text_field :apellido, class: 'form-control' %>
          <%= empleado_form.text_field :departamento, class: 'form-control' %>
          <%= empleado_form.text_field :responsable_area, class: 'form-control' %>
          <%= empleado_form.text_field :extension, class: 'form-control' %>
        <%end %>
        <!--
      <h2>Tipo de Equipo</h2>
      <%#= f.fields_for :tipo_equipo do |tipoequipo_form| %>
        <%#= tipoequipo_form.text_field :tipo_equipo %>
      <%# end %>
      <h2>Marca</h2>
      <%#= f.fields_for :marca do |marca_form| %>
        <%#= marca_form.text_field :marca %>
      <%# end %>
      <h2>Estado</h2>
      <%#= f.fields_for :estado do |estado_form| %>
        <%#= estado_form.text_field :estado %>
      <%# end %>
      <h2>Equipo</h2>
      <%#= f.fields_for :equipo do |equipo_form| %>
        <%#= equipo_form.text_field :serie %>
        <%#= equipo_form.text_field :modelo %>
        <%#= equipo_form.text_field :service_tag %>
        <%#= equipo_form.text_field :ip %>
        <%#= equipo_form.text_field :garantia %>
      <%# end %>
      -->
        <%= f.button :submit, class: 'btn btn-success' do %>
          <%= image_tag('icons/update.svg')%>
          <span>Update</span>
        <%end%>   
        <%= link_to home_index_path, class: 'btn btn-danger' do %> Cancel
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
          </svg>
        <% end %>
      <%end %>
    </div>
    <%= render 'partials/footer' %>
</div>

app/views/pages/index.html.erb
<div class="d-flex flex-column min-vh-100">
  <%= render 'partials/header' %> 
  <div class="container">
    <table class="table table-striped table-hover table-dark table-bordered mt-5">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Company</th>
        <th scope="col">Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Department</th>
        <th scope="col">Manager</th>
        <th scope="col">Phone</th>
        <th scope="col">Actions</th>
        <th scope="col">More</th>
      </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @empresa.each do |empresas| %>
          <tr>
            <th scope="row"><%= empresas.id %></th>
            <td><%= empresas.nombre %></td>
          <% empresas.empleados.each do |empleado| %>
            <td><%= empleado.nombre %></td>
            <td><%= empleado.apellido %></td>
            <td><%= empleado.departamento %></td>
            <td><%= empleado.responsable_area %></td>
            <td><%= empleado.extension %></td>
          <% end %>
            <td>
              <%if current_user%>
                <%= link_to new_page_path(empresas), class:'btn btn-success btn-sm' do %> New Register
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-floppy-fill" viewBox="0 0 16 16">
                    <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0H3v5.5A1.5 1.5 0 0 0 4.5 7h7A1.5 1.5 0 0 0 13 5.5V0h.086a1.5 1.5 0 0 1 1.06.44l1.415 1.414A1.5 1.5 0 0 1 16 2.914V14.5a1.5 1.5 0 0 1-1.5 1.5H14v-5.5A1.5 1.5 0 0 0 12.5 9h-9A1.5 1.5 0 0 0 2 10.5V16h-.5A1.5 1.5 0 0 1 0 14.5z"/>
                    <path d="M3 16h10v-5.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5zm9-16H4v5.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5zM9 1h2v4H9z"/>
                  </svg>
                <%end%>  
                <%= link_to page_path(empresas), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm' do %> Delete
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                  </svg>
                <%end%>
                <%= link_to edit_page_path(empresas), class: 'btn btn-primary btn-sm' do %> Edit
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2z"/>
                    <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466"/>
                  </svg>
                <%end%>
                <td><!-- otra forma de hacer el boton eliminar 
                  <%= button_to page_path(empresas), method: :delete, form: { data: { turbo_confirm: "¿Estás seguro?" } }, class: 'btn btn-danger btn-sm' do %> Delete
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                      <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                    </svg>
                  <%end%> -->
                  <% @empresa.each do |empresa_csv|%>
                    <% if empresa_csv.id == empresas.id %>
                      <%= link_to 'Export CSV', export_csv_path(empresa_csv), class: 'btn btn-info btn-sm'%>
                    <%end%>  
                  <%end%>
                  <% @empresa.each do |empresa_pdf|%>
                    <% if empresa_pdf.id == empresas.id %>
                      <%= link_to 'Export PDF', export_pdf_path(empresa_pdf, format: :pdf), target: '_blank', class: 'btn btn-info btn-sm'%>
                    <%end%>  
                  <%end%>  
                </td>
              <%else%>
                <p>sign in or register to execute actions</p>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to home_path do %> Go to home
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
      </svg>
    <%end%>
  </div>
  <%= render 'partials/footer' %>
</div>

app/views/pages/page.html.erb
<h1>This is the secret page 2</h1>

app/views/pages/secret.html.erb
<h1>This is the secret page</h1>

app/views/partials/_footer.html.erb
<footer class="footer mt-auto py-3 text-muted">
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h6 class="text-center"> © 2024 Copyright </h6>
      </div>
      <div class="col-sm">
        <h6 class="text-center">Spark S,A.</h6>
      </div>
      <div class="col">
        <h6 class="col-sm text-center">Made with <%= image_tag 'love.png', style: "height: 20px" %> by Osman Santeliz.</h6>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/">
            <h3 class="">Tech Inventory</h3>
          </a>
          <% if current_user %>
            <h1 class="text-center rounded bg-info bg-opacity-10">Welcome, <small class="text-muted text-capitalize"><%= current_user.name %></small></h1>
            <div class="btn btn-outline-danger btn-sm">
              <%= link_to user_session_path(current_user), data: { turbo_method: :delete }, :class => "btn" do%> Log out
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"/>
                  <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                </svg>
              <%end%>
            </div>
            <%else%>
            <div>
              <%= link_to login_path, class: 'btn btn-outline-success' do %> Login
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                  <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                </svg>
              <%end%>
            </div>
            <div>
              <%= link_to user_register_path, class: 'btn btn-outline-success' do %> Register
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                  <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                  <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                </svg>
              <%end%>
            </div>  
          <% end %>
          <%=image_tag 'logo.jpeg', class: 'rounded-circle', style: "height: 100px"%>
          <%= @current_time %>
        </div>
      </nav>
    </div>
  </div>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="d-flex flex-column min-vh-100">
  <%=render 'partials/header'%>
  <div class="container border rounded my-5">
    <div class="row justify-content-center align-items-center">
        <div class="col">
          <h1 class="text-center bg-light text-muted rounded">Users Login</h1>
          <%= form_with model: @user, url: user_sessions_path do |f| %>
            <form>
              <div class="row">
                <div class="col">
                  <div class="form-group">
                    <%= f.label :name%>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <div class="input-group-text bg-info bg-opacity-75">
                          <i><%= image_tag 'icons/user.svg'%></i>
                        </div>  
                      </div> 
                      <%= f.text_field :name, autofocus: true, required: true, placeholder: 'Name', class: 'form-control bg-info bg-opacity-10 border border-info', id: 'txtsessionname'%> 
                    </div>
                  </div>
                </div>
                <div class="col-sm">
                  <div class="form group">
                    <%= f.label :password%>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <div class="input-group-text bg-info bg-opacity-75">
                          <i><%= image_tag 'icons/key.svg'%></i>
                        </div>  
                      </div>
                      <%= f.password_field :password, required: true, placeholder: 'Password', class: 'form-control bg-info bg-opacity-10 border border-info', id: 'txtsessionpass'%>  
                    </div>
                  </div>  
                </div>  
              </div>
              <div class="row mt-5">
                  <p class="d-grid gap-2 col-6 mx-auto">
                    <%= f.button :submit, :class => "btn btn-outline-success" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                        <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                      </svg>
                      <span> Sign In </span>
                    <%end%>
                    <%= link_to home_index_path, :class => "btn btn-outline-danger" do %> Cancel
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                      </svg>                
                    <%end%>
                  </p>
                </div>
            </form>
          <% end %>
        </div>
    </div>
    <%= link_to home_index_path do %> Home
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
      </svg>
    <% end %>
  </div>
  <%= render 'partials/footer' %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Tabla de Usuarios</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>